#  if [ -z "$1" ]; then
#    echo Input Password is missing
#    exit 1
#    fi
#
#    source common.sh
#    component=shipping
#    MAVEN
#
#    dnf install mysql -y
#    for file in schema app-user master-data; do
#    mysql -h mysql-dev.rdevopsb85.online -uroot -p$1 < /app/db/$file.sql
#    done

- name: Install MySQL Client
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: Load Schema
  ansible.builtin.shell: |
    mysql -h mysql-dev.shamdevops.online -uroot -pRoboShop01 < /app/db/schema.sql

- name: Load App User
  ansible.builtin.shell: |
    mysql -h mysql-dev.shamdevops.online -uroot -pRoboShop01 < /app/db/app-user.sql

- name: Load Master Data
  ansible.builtin.shell: |
    mysql -h mysql-dev.shamdevops.online -uroot -pRoboShop01 < /app/db/master-data.sql


