# - name: Load Maven
#   ansible.builtin.import_role:
#     name: common
#     tasks_from: maven
#
# - name: Install MySQL client
#   ansible.builtin.dnf:
#     name: mysql
#     state: installed
#
# - name: Load Schema
#   ansible.builtin.shell: mysql -h mysql-dev.rdevopsb85.online -u{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/shipping:DB_USER token={{ token }} url=http://vault-internal.rdevopsb85.online:8200') }} -p{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/shipping:DB_PASS token={{ token }} url=http://vault-internal.rdevopsb85.online:8200') }} < /app/db/{{ item }}.sql
#   loop:
#     - schema
#     - app-user
#     - master-data
#
#


- name: Load common main
  ansible.builtin.import_role:
    name: common

- name: Load Docker
  ansible.builtin.import_role:
    name: common
    tasks_from: docker

- name: Launch Docker Container
  community.docker.docker_container:
    name: shipping
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/shipping
    ports:
      - "8080:8080"
    env:
      CART_ENDPOINT: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/shipping:CART_ENDPOINT token={{ token }} url=http://vault-internal.shamidevops.online:8200') }}"
      DB_HOST: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/shipping:DB_HOST token={{ token }} url=http://vault-internal.shamidevops.online:8200') }}"

- name: Schema Container
  loop:
    - app-user
    - schema
    - master-data
  community.docker.docker_container:
    name: shipping-schema-{{ item }}
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
    env:
      DB_TYPE: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/shipping:DB_TYPE token={{ token }} url=http://vault-internal.shamidevops.online:8200') }}"
      APP_GIT_URL: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/shipping:APP_GIT_URL token={{ token }} url=http://vault-internal.shamidevops.online:8200') }}"
      DB_HOST: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/shipping:DB_HOST token={{ token }} url=http://vault-internal.shamidevops.online:8200') }}"
      DB_USER: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/shipping:DB_USER token={{ token }} url=http://vault-internal.shamidevops.online:8200') }}"
      DB_PASS: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/shipping:DB_PASS token={{ token }} url=http://vault-internal.shamidevops.online:8200') }}"
      SCHEMA_FILE: "db/{{  item }}.sql"
