#dnf module disable nginx -y
#dnf module enable nginx:1.24 -y
#dnf install nginx -y
#cp nginx.conf /etc/nginx/nginx.conf
#rm -rf /usr/share/nginx/html/*
#curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
#cd /usr/share/nginx/html
#unzip /tmp/frontend.zip
#systemctl enable nginx
#systemctl restart nginx
-
- name: disable nginx default version
  ansible.builtin.shell: dnf module disable nginx -y

- name: Enable nginx version 1.24
  ansible.builtin.shell: dnf module enable nginx:1.24 -y

- name: Install nginx
  ansible.builtin.dnf:
      name: nginx
      state: Installed

- name: Copy nginx config
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Remove nginx default content
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state:  absent

- name: Create nginx http directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: directory

- name: Download nginx content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /usr/share/nginx/html/

- name: Start nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted



