#if [ -z "$1" ]; then
#echo Input Password is missing
#exit 1
#fi
#
#dnf install mysql-server -y
#systemctl enable mysqld
#systemctl start mysqld
#mysql_secure_installation --set-root-pass $1

- name: Install MySQL
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Start MySQL
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: yes

- name: Set Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1