- name: Download Hashicorp Repo file
  ansible.builtin.copy:
    src : hashicorp.repo
    dest : /etc/yum.repos.d/hashicorp.repo

- name : Install Hashicorp Vault
  ansible.builtin.dnf:
    name : vault
    state : installed