- name: Increase disk partition size
  ansible.builtin.shell: growpart /dev/nvme0n1 4
  ignore_errors: yes

- name: Update Log Vol Sizes
  loop: "{{ lvm_disks }}"
  community.general.lvol:
    vg: "{{ item.vgname }}"
    lv: "{{ item.lvmname }}"
    size: "{{ item.size }}"
    resizefs: true
