- name: Set Prompt
  ansible.builtin.shell: set-prompt {{ component }}-{{ env }}

- name: Increase disk partition size
  ansible.builtin.shell: growpart /dev/nvme0n1 4
  ignore_errors: yes

- name: Increase disk size
  ansible.builtin.shell: lvextend -r -L {{ item.size }}G /dev/mapper/{{ item.lvm }}
  loop: "{{ lvm_sizes }}"
  ignore_errors: yes

#- name: Node exporter
#  ansible.builtin.import_role:
#    name: common
#    tasks_from: node_exporter
