#  MAVEN() {
#    dnf install maven -y
#
#    APP_PREREQ
#    mvn clean package
#    mv target/${component}-1.0.jar ${component}.jar
#
#    SYSTEMD
#  }

- name: Install Maven
  ansible.builtin.dnf:
    name: maven
    state: installed

- name: Load App Pre-Req
  ansible.builtin.include_role:
    name: common
    tasks_from: app-prereq.yml

- name: install Maven Dependencies
  ansible.builtin.shell: mvn clean package ; mv target/{{component}}-1.0.jar {{component}}.jar
  args:
    chdir: /app

- name: Load SystemD Service
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd.yml
