#  SYSTEMD() {
#    systemctl daemon-reload
#    systemctl enable ${component}
#    systemctl start ${component}
#  }

- name: Copy component service file
  ansible.builtin.template:
    src: "{{ component }}.service"
    dest: /etc/systemd/system/{{component}}.service

- name: Start Service
  ansible.builtin.systemd:
    name: "{{ component }}"
    daemon_reload: true
    enabled: true
    state: restarted


